import type { Metadata } from "next";
/* eslint-disable react/no-unescaped-entities */

export const metadata: Metadata = {
  title: "Privacy Policy - Rally",
  description:
    "Rally privacy policy describing data collection, use, sharing, retention, and your rights.",
};

export default function PrivacyPolicy() {
  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="text-3xl font-bold mb-3">Rally Privacy Policy</h1>
      <p className="text-sm text-foreground/60 mb-6">
        Last updated: February 13, 2026
      </p>
      <p className="mb-6">
        Rally ("Rally," "we," "us," or "our") provides a mobile application to
        help users plan and coordinate live events. This Privacy Policy explains
        what information we collect, how we use it, when we share it, and your
        rights and choices.
      </p>
      <p className="mb-10">
        Contact:{" "}
        <a
          href="mailto:henriquez.gus99@gmail.com"
          className="underline hover:opacity-80"
        >
          henriquez.gus99@gmail.com
        </a>
      </p>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">1. Scope</h2>
        <p>
          This Privacy Policy applies to personal information processed through
          the Rally mobile application and related services (the "Service"). It
          does not apply to third-party websites, apps, or services that are not
          controlled by Rally.
        </p>
      </section>

      <section className="space-y-6 mb-10">
        <h2 className="text-2xl font-semibold">2. Information We Collect</h2>

        <div className="space-y-4">
          <h3 className="text-xl font-medium">
            2.1 Information you provide directly
          </h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Account and authentication data: phone number used for one-time
              passcode (OTP) sign-in.
            </li>
            <li>Profile information</li>
            <li>Event and planning content</li>
            <li>Event Participation data</li>
            <li>
              Communications: information you send when contacting us for
              support or account requests.
            </li>
          </ul>
        </div>

        <div className="space-y-4">
          <h3 className="text-xl font-medium">
            2.2 Information collected automatically
          </h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Device/app information: platform, app version, generated device
              identifier, and push notification token.
            </li>
            <li>
              Usage analytics: in-app interaction events (for example
              authentication and event interaction events), internal identifiers
              (when applicable), timestamps, and event properties.
            </li>
            <li>
              Service and diagnostic data: operational logs and metadata
              generated by our infrastructure/providers, which may include IP
              address and request timestamps.
            </li>
          </ul>
        </div>

        <div className="space-y-4">
          <h3 className="text-xl font-medium">
            2.3 Data from permissions and device features
          </h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Notifications permission: used to register your device for push
              notifications and deliver event-related notifications.
            </li>
            <li>
              Calendar permission: used only when you choose to add an event to
              your calendar.
            </li>
            <li>
              Clipboard access: when you open the "Join Invite" screen, Rally
              checks clipboard text to detect an invite link or code to help you
              join quickly.
            </li>
            <li>
              Maps and geocoding: when you search or select locations, location
              queries and place lookups are processed through our maps
              integration.
            </li>
          </ul>
          <p>
            You can control permissions at any time in your device settings.
          </p>
        </div>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">3. How We Use Information</h2>
        <p>We use personal information to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Create and manage accounts and authenticate users.</li>
          <li>
            Enable core features (event creation, invite access, RSVPs, ticket
            coordination, notifications, and profile display).
          </li>
          <li>
            Provide in-app and push notifications based on your preferences.
          </li>
          <li>
            Support mapping, place search, and geocoding for event locations.
          </li>
          <li>Maintain, troubleshoot, secure, and improve the Service.</li>
          <li>
            Enforce our Terms, detect misuse, and comply with legal obligations.
          </li>
        </ul>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">
          4. Legal Bases for Processing (EEA/UK)
        </h2>
        <p>
          If you are in the EEA or UK, we process personal data under one or
          more of these legal bases:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Contract: to provide the Service you request.</li>
          <li>
            Legitimate interests: to secure, operate, and improve the Service.
          </li>
          <li>
            Consent: for permissions such as push notifications and calendar
            access where applicable.
          </li>
          <li>Legal obligation: to comply with applicable law.</li>
        </ul>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">5. How We Share Information</h2>
        <p>
          We do not sell personal information and do not share personal
          information for cross-context behavioral advertising.
        </p>
        <p>We may share information with:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            Infrastructure and backend providers (for example, Supabase) for
            authentication, database, server functions, and storage/processing.
          </li>
          <li>
            Maps and location providers (for example, Google Maps Platform APIs)
            for place lookup and geocoding support.
          </li>
          <li>
            Notification delivery providers (for example, Expo and platform push
            services such as APNs) to deliver notifications.
          </li>
          <li>
            Platform/device services you choose to use: calendar providers and
            native share targets when you explicitly add events to calendar or
            share invites.
          </li>
          <li>
            Legal/compliance recipients: law enforcement, regulators, courts, or
            other parties when required by law or to protect rights and safety.
          </li>
          <li>
            Successors in a business transfer: in connection with a merger,
            acquisition, financing, or asset sale.
          </li>
        </ul>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">6. Data Retention</h2>
        <p>
          We retain personal information for as long as needed for the purposes
          described in this policy, including to provide the Service, maintain
          security, and comply with law.
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Account/profile data: retained while your account is active.</li>
          <li>
            Event and participation data: retained until deleted by users or
            removed through account deletion workflows.
          </li>
          <li>
            Notifications: notification-related records are retained for a
            limited period consistent with operational needs and then deleted or
            de-identified.
          </li>
          <li>
            Analytics records: retained for product/security analysis and may be
            de-identified or aggregated over time.
          </li>
          <li>
            Logs and diagnostics: retained according to operational and security
            needs.
          </li>
        </ul>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">7. Account and Data Deletion</h2>
        <p>You can request deletion by:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            Using the in-app delete option: Profile -&gt; Delete Account, or
          </li>
          <li>
            Emailing us at{" "}
            <a
              href="mailto:henriquez.gus99@gmail.com"
              className="underline hover:opacity-80"
            >
              henriquez.gus99@gmail.com
            </a>
            .
          </li>
        </ul>
        <p>
          When account deletion is processed, Rally removes or deactivates
          associated account data, including deleting your auth account/profile
          and removing event membership/participation records tied to your
          account. Events you own are soft-deleted (marked deleted and no longer
          available in the app experience). Some data may remain where required
          by law, for fraud/security prevention, dispute handling, or in
          de-identified/aggregated form.
        </p>
      </section>

      <section className="space-y-6 mb-10">
        <h2 className="text-2xl font-semibold">8. Your Rights and Choices</h2>

        <div className="space-y-4">
          <h3 className="text-xl font-medium">8.1 General controls</h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>Update profile details in-app.</li>
            <li>
              Manage notification preferences in-app and at the device level.
            </li>
            <li>Request account/data deletion using the methods above.</li>
          </ul>
        </div>

        <div className="space-y-4">
          <h3 className="text-xl font-medium">8.2 EEA/UK rights</h3>
          <p>
            Subject to applicable law, you may request access, correction,
            deletion, restriction, portability, and objection to certain
            processing.
          </p>
        </div>

        <div className="space-y-4">
          <h3 className="text-xl font-medium">8.3 California privacy rights</h3>
          <p>
            California residents may have rights to know, access, correct, and
            delete personal information, and to receive information about data
            practices. Rally does not sell personal information or share it for
            cross-context behavioral advertising.
          </p>
          <p>
            To exercise rights, contact:{" "}
            <a
              href="mailto:henriquez.gus99@gmail.com"
              className="underline hover:opacity-80"
            >
              henriquez.gus99@gmail.com
            </a>
            .
          </p>
        </div>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">9. Children&apos;s Privacy</h2>
        <p>
          Rally is not intended for children under 13, and we do not knowingly
          collect personal information from children under 13. If we learn that
          we collected such information, we will take steps to delete it.
        </p>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">10. Security</h2>
        <p>
          We use reasonable administrative, technical, and organizational
          measures to protect personal information. No system is completely
          secure, and we cannot guarantee absolute security.
        </p>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">11. International Processing</h2>
        <p>
          Depending on where you use Rally, your information may be processed in
          countries other than your own, including where our service providers
          operate.
        </p>
      </section>

      <section className="space-y-4 mb-10">
        <h2 className="text-2xl font-semibold">12. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. If we make
          material changes, we will update the "Last updated" date and post the
          revised version.
        </p>
        <p>
          Operational details may change over time without materially changing
          our core privacy practices.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">13. Contact</h2>
        <p>For privacy requests or questions, contact:</p>
        <p>
          <a
            href="mailto:henriquez.gus99@gmail.com"
            className="underline hover:opacity-80"
          >
            henriquez.gus99@gmail.com
          </a>
        </p>
      </section>
    </main>
  );
}
